### ISSUE TITLE
Some mistake have happen in Alienworldsbot

### ISSUE THREAD

**Issue by Timurbudlian** [SmartBotBlack/alienworldsbot#5]
Hello!

Pls can you explane to me what i did wrong.

Here is a log:

C:\Users\Acer-RBT3>cd alienworldsbot

C:\Users\Acer-RBT3\alienworldsbot>npm run mine

> alienworldsbot@1.0.0 mine
> node ./dist/index.js

Proxies not found!
wax cookies.txt: Run!
wax cookies.txt: Browser is waiting in the launch queue
wax cookies.txt: Browser run
wax cookies.txt: Add cookies
wax cookies.txt: Click Login Page
wax cookies.txt: Click Login Page
wax cookies.txt: Click Login Page
wax cookies.txt: Click Login Page
wax cookies.txt: Click Login Page
wax cookies.txt: Click Login Page
wax cookies.txt: Click Login Page
wax cookies.txt: Click Login Page
wax cookies.txt: Click Login Page
wax cookies.txt: Click Login Page
wax cookies.txt: Click Login Page
wax cookies.txt: Click Login Page
wax cookies.txt: Click Login Page
wax cookies.txt: Click Login Page
wax cookies.txt: Click Login Page
wax cookies.txt: Click Login Page
wax cookies.txt: Click Login Page
wax cookies.txt: Click Login Page
wax cookies.txt: Click Login Page
wax cookies.txt: Click Login Page
wax cookies.txt: Click Login Page
wax cookies.txt: Click Login Page
wax cookies.txt: Click Login Page
wax cookies.txt: Click Login Page
(node:5756) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
wax cookies.txt: Throw Error
wax cookies.txt: Error: Protocol error (Runtime.callFunctionOn): Target closed.
wax cookies.txt: Can't take screenshot
Error: Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed.
    at CDPSession.send (C:\Users\Acer-RBT3\alienworldsbot\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:208:35)
    at ExecutionContext._evaluateInternal (C:\Users\Acer-RBT3\alienworldsbot\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:204:50)
    at ExecutionContext.evaluate (C:\Users\Acer-RBT3\alienworldsbot\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:110:27)
    at DOMWorld.evaluate (C:\Users\Acer-RBT3\alienworldsbot\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:91:24)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
wax cookies.txt: Browser sleep: 10sec
C:\Users\Acer-RBT3\alienworldsbot\node_modules\puppeteer\lib\cjs\puppeteer\common\assert.js:26
        throw new Error(message);
              ^

Error: Protocol error: Connection closed. Most likely the page has been closed.
    at Object.assert (C:\Users\Acer-RBT3\alienworldsbot\node_modules\puppeteer\lib\cjs\puppeteer\common\assert.js:26:15)    at Page.close (C:\Users\Acer-RBT3\alienworldsbot\node_modules\puppeteer\lib\cjs\puppeteer\common\Page.js:2008:21)
    at C:\Users\Acer-RBT3\alienworldsbot\dist\task.js:133:19
    at Generator.next (<anonymous>)
    at C:\Users\Acer-RBT3\alienworldsbot\dist\task.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\Acer-RBT3\alienworldsbot\dist\task.js:4:12)
    at browserSleep (C:\Users\Acer-RBT3\alienworldsbot\dist\task.js:131:49)
    at C:\Users\Acer-RBT3\alienworldsbot\dist\task.js:299:48
    at Generator.throw (<anonymous>)

Why Login Page was not Clicked? How can i correct this?

Thanks for your help.

**Comment by harpreet9629** [comment]
its still working?

**Comment by voodee** [comment]
Please check again.
